### ISSUE TITLE
Don't automatically open things in the browser

### ISSUE THREAD

**Issue by martinheidegger** [finnp/help-out#3]
It is very problematic to automatically open links in the browser. You don't know what is going to open and what you are expected to do. A "confirm" button would be good imho.

**Comment by finnp** [comment]
Yeah good idea. Right now there is a `--no-open` flag. But your suggestion sounds great.

**Comment by finnp** [comment]
Update to 1.1.0. It now asks you what to do (open browser, show another one, next)
